### ISSUE TITLE
Website Does not show all Languages

### ISSUE THREAD

**Issue by Irtiza90** [was07/Hello-Worlds#23]
[Hello-Worlds](https://was07.github.io/Hello-Worlds/), does not show all of the languages

I did some digging in the JS code and found out that 2 languages were missing
so i basically rewrote that part
I don't know much JS so hopefully this is good enough
```js
fetch('https://api.github.com/repos/was07/Hello-Worlds/contents/programs').then(
    function(lang) {
      lang.json().then(
          function(langs) {
            for (let x in langs) { console.log(langs[x].name.split(".")[0]) }
          }
      )
    }
)
```
In this i'm just console logging it but do whatever you want with it

**Comment by was07** [comment]
I see how you want to do it but there is a slight problem with it, the names don't come so great like C# comes like Csharp

**Comment by was07** [comment]
And I think the website shows all the languages, the problem is with the number it shows, which is two more than the actual

**Comment by was07** [comment]
> And I think the website shows all the languages, the problem is with the number it shows, which is two more than the actual

i take that back the number is accurate

**Comment by Irtiza90** [comment]
Alright, That's Fair enough

**Comment by Irtiza90** [comment]
i also found out that in the code you don't add them if they are HTML or CSS
Both Urls [1](https://api.github.com/repos/was07/Hello-Worlds/languages) and [2](https://api.github.com/repos/was07/Hello-Worlds/contents/programs) Returns 36 results, in (1) two of them are not accepted(HTML, CSS) so that's why

**Comment by was07** [comment]
We are not going to include html or css.

Without them, there should be 36 files in `programs`. But the urls (with html and css) give us 36, meaning there are 34 valid languages. Probably means it doesn't recognize the language of 2 files... In that case this way of the list of languages isn't going to work.

**Comment by was07** [comment]
Found out it is Algol and F# that Github doesn't recognize \

**Comment by Irtiza90** [comment]
> Found out it is Algol and F# that Github doesn't recognize 

so we can hardcode them maybe?
